print('¿Qué sale de la cruza de un mono y un pato?')
input()
print('¡Un monopatín!')
print()
print('¿Por qué vuelan los pájaros pa\'l sur?')
input()
print('Porque caminando tardarían muchísimo!')
print()
print('¿En qué se parecen una familia, un bombero y un barco?')
input()
print('No sé... ¿En qué se parecen?')
input()
print('En que el bombero y barco tienen casco.')
input()
print('¿Y la familia?', end='')
print(' -Bien, gracias.')